name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Run Spotless Check
      run: ./gradlew spotlessCheck
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run Tests
      run: ./gradlew test